### ISSUE TITLE
rustc fails to build

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#100]
```
mkdir: cannot create directory 'tmp/dist': Permission denied
make: *** [/usr/src/pkg/wrk/rustc/src/rustc-1.16.0-src/mk/dist.mk:132: prepare-host-dirs-dir-x86_64-unknown-linux-gnu] Error 1
make: *** [/usr/src/pkg/wrk/rustc/src/rustc-1.16.0-src/mk/install.mk:21: install] Error 2
```

I did actually read the README and `su` (not `sudo`) to build as well.

Isn't there some way we can force it to use `$PKGMK_WORK_DIR` or something?

**Comment by rtlanceroad** [comment]
I don't know what's wrong with it, but I built it successfully with root login shell, that is `su -l`.

**Comment by onodera-punpun** [comment]
I didn't actually build with `su -l`, just root (`su). I see you updated the README already, so I'll close this :).
