### ISSUE TITLE
remove xorg-libxkbcommon 

### ISSUE THREAD

**Issue by muphil** [6c37/crux-ports#101]
libxkbcommon has been included in the opt repo. The name is libxkbcommon.
please fix the denpendencies filed in fcitx and possibly remove 6c37/xorg-libxkbcommon.

**Comment by rtlanceroad** [comment]
Sorry for my mistakenly action and very thankful from your report, I just removed `xorg-libxkbcommon` by commit f8e2b4819341d37ceadc2bfd24b611a038e7aba5 and fixed `fcitx` dependency by commit cf24a27f2ef0abc811f3ff7f4f3c4dc4cd95659e . :)
