### ISSUE TITLE
Rust 1.17.0 issues.

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#102]
About 3 days ago, I received an update about `rustc`, which is 1.17.0 release, then I used my spare time to get `Cargo` aka Rust Package Manager and `rustc` to build, then I failed  several times. The reason they did this is because they think their `Cargo` _CRAP_  is [mature enough and mark removal for `Makefile`](https://blog.rust-lang.org/2017/04/27/Rust-1.17.html):
```
This release marks the removal of the old Makefile based build system. The new system, announced in Rust 1.15, is written in Rust and primarily uses Cargo to drive the build. It is now mature enough to be the only build system.
```
Now. I am quite frustrated by their move and I WONT do anything for their _CRAP_!!! Hopefully some other maintainers or volunteers who are interested this could  do this.

**Comment by rtlanceroad** [comment]
I see there is also binary for it, just note here.

**Comment by onodera-punpun** [comment]
Some package templates for inspiration:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rust
https://git.alpinelinux.org/cgit/aports/tree/community/rust/APKBUILD

**Comment by rtlanceroad** [comment]
Thanks for the reference, will see it later...

**Comment by rtlanceroad** [comment]
@onodera-punpun I think I'll leave this to you. I can't download cargo because I can't download cargo nightly from s3.amazonaws.com.
```
curl: (7) Failed to connecte to s3.amazonaws.com port 443: Connection timed out
```
The `rustc` Pkgfile looks like this:
```
# Description: The Rust programming language compiler and utilities.
# URL:         http://www.rust-lang.org
# Maintainer:  6c37 Team, https://github.com/6c37/crux-ports/issues
# Depends on:


name=rustc
version=1.16.0
release=1
source=(https://static.rust-lang.org/dist/$name-$version-src.tar.gz) 

build() {
	cd $name-$version-src

	./configure --prefix=/usr --disable-docs --release-channel=stable

	make CFLAGS="$CFLAGS -fPIC -w"
	make DESTDIR=$PKG install
	
	rm -rf $PKG/usr/lib/rustlib/{components,manifest-rustc,rust-installer-version}
	rm -rf $PKG/usr/share/doc
}
```

Could you update it for us?

**Comment by rtlanceroad** [comment]
The `bootstrap.py` will download `rust` `rust-std` and `Cargo nightly`(Where I failed to download) three files automatically and extract properly, then build will start, I prefer this way. Also you can use a different cargo build as you like.

**Comment by onodera-punpun** [comment]
Yeah, I'll try something, I'm pretty sure firefox will depend on rust in their next release and seamonkey in a few versions, so I've been wanting to package this for a while.

**Comment by onodera-punpun** [comment]
Fixed.

**Comment by rtlanceroad** [comment]
Thanks

**Comment by onodera-punpun** [comment]
So because rustc and cargo are bundled in the official rust packages, and because firefox will depend on both cargo and rustc I tried to port rustc, but it's seems like anything rust related is an absolute pain to package.

I suspect this is done on purpose to "gently push" people to use their shitty package manager and rustup shell script instead of distro packages. Anyways, enough conspiracy theories, this is the current cargo Pkgfile I have:

```bash
# Description: The Rust package manager.
# URL:         https://crates.io/
# Maintainer:  6c37 Team, https://github.com/6c37/crux-ports/issues
# Depends on:  rustc libgit2


name=cargo
version=0.18.0
release=1
source=(
	https://github.com/rust-lang/$name/archive/$version.tar.gz
	https://static.rust-lang.org/dist/cargo-$version-x86_64-unknown-linux-gnu.tar.gz
)

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--release-channel=stable \
		--enable-optimize \
		--cargo=$SRC/$name-$version-x86_64-unknown-linux-gnu/$name/bin/$name

	make LIBGIT2_SYS_USE_PKG_CONFIG=1
	make DESTDIR=$PKG install
}
```

This one however fails with the following error: 

```
sh: 0: Can't open /usr/src/pkg/wrk/cargo/src/cargo-0.18.0//src/rust-installer/gen-installer.sh
make: *** [Makefile:399: target/x86_64-unknown-linux-gnu/release/dist/cargo-0.18.0-x86_64-unknown-linux-gnu.tar.gz] Error 127
```

I might try fixing this someday.

**Comment by rtlanceroad** [comment]
Yeah I think so.  `Cargo` is a real pain to package. But Is it possible to build firefox with pre-compiled cargo binary?  If possible,  that would make it less painful. Also If it's _really_ necessary, we can creat a binary repo to package binary packages, like thunderbird-bin, palemoon-bin, or  google chrome etc to satisfy users' needs, even It's go far beyond CRUX KISS. Btw I've already dropped firefox for a while and fully switched to qupzilla, chromium etc, palemoon is even expermental to build with gcc >=5...

**Comment by rtlanceroad** [comment]
@onodera-punpun Could you update rustc to 1.18.0?
