### ISSUE TITLE
dwarffortress

### ISSUE THREAD

**Issue by xcko** [6c37/crux-ports#104]
By default dwarf fortress install to /opt, but on CRUX /opt is reserved for user compiled programs, I think it should be installed to /usr/share instead. 

I can make a patch if you want.

**Comment by rtlanceroad** [comment]
I think @onodera-punpun is intended to install it to /opt on purpose, so I guess onidera doesn't want to mess games with applications, so he does it for any convience, I am fine with that. Yeah you are right also, /opt is designed for optional packages, especially user compile programs,  according to traditional filesystem hierarchy standrads. We will see onodera's saying.

**Comment by onodera-punpun** [comment]
I don't exactly remember, but I think I had reasons to use `/opt`, though maybe that reason was just because I couldn't get it to work otherwise. If you can get it to work using `/usr/share` I'll merge it yes :)
