### ISSUE TITLE
graphicsmagick signing

### ISSUE THREAD

**Issue by maraku** [6c37/crux-ports#107]
the new graphicsmagick has a signing error. could someone please sign it?
```
chroot $ pwd
/usr/ports/6c37/graphicsmagick
chroot $ fakeroot pkgmk
=======> ERROR: Signature mismatch found:
MISMATCH        signify
=======> ERROR: Building '/usr/ports/pkg/graphicsmagick#1.3.26-1.pkg.tar.xz' failed.
```

**Comment by rtlanceroad** [comment]
Interesting, I don't get a signing error.

**Comment by rtlanceroad** [comment]
After test in 2 CRUX hosts and 1 virtualbox, I can confirm that nothing's wrong with graphicsmagick's signature. For now, I close it.

**Comment by maraku** [comment]
it was a silly mistake on my part. i forgot to copy the .pub keys of extra repos while chroot testing. sorry. thanks anyways for looking into it.
