### ISSUE TITLE
rustc 1.19.0

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#109]
@onodera-punpun Could you do update for rustc? It failed with `exit with code 101` for me with no further information....

**Comment by onodera-punpun** [comment]
Woops, sorry, I was on holiday :)

**Comment by rtlanceroad** [comment]
No problem :)

**Comment by rtlanceroad** [comment]
@onodera-punpun If you got time, try building `seamonkey`, I've built it for nearly 20 times, but still no success...

**Comment by onodera-punpun** [comment]
I think `seamonkey` is still in 2.48 beta1, or are you talking about that? I'll try building it with rust once the official release releases, which should be very soon hopefully :).

**Comment by rtlanceroad** [comment]
https://www.seamonkey-project.org/releases/seamonkey2.48/ Kinda confusing to me. I know whatever from downloading or system requirements,  it refers to 2.48 beta1, but why not call this release a seamonkey2.48beta1 instead of seamonkey2.48? Why does the developers recommend a beta version for common users. It must be something strange which leads me to think this 2.48 release is not 2.48beta1.
