### ISSUE TITLE
New boost breaks openimageio build with Python

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#111]
Disabling Python seems to fix the build, but we should re-enable python with the new release.

There seems to be a patch, but I can't get it to apply to the current release: https://github.com/OpenImageIO/oiio/commit/f67ae87d820a12c0451f8877e735c49b44dbbf63

**Comment by rtlanceroad** [comment]
To be honest, I don't find any reason why we need build oiio with python2/3 bindings... or is there any software relying on such feature? I don't know. In the past, we built it as what CMakefile.txt defined, that was, built bindings for python2, but now i think about a little bit, we can turn python binding off, no matter which python veesion is.

**Comment by onodera-punpun** [comment]
Blender prints this on startup: `Color management: using fallback mode for management`, but it might have done so before as well. I'm not sure if blender requires the python binding (since Blender uses lots of python under the hood).
