### ISSUE TITLE
kicad libraries 

### ISSUE THREAD

**Issue by mwsoft69** [6c37/crux-ports#113]
Why aren't the kicad component  libraries installed by default. Its no big deal to get them and install them, but it would be nice if it works out of the box.

Thanks,
Mitch

**Comment by rtlanceroad** [comment]
Thanks for the advice. It was the idea original from @rmull . Remember we are source-based distro, third party libraries will cause footprint mismatch if there are some commits pushed by devs from time to time. To guarantee no footprint mismatch, current solution seems better, at least in my opinion. :)

**Comment by mwsoft69** [comment]
Sounds good! Yeah the current solution works just fine.

**Comment by rtlanceroad** [comment]
Closing.
