### ISSUE TITLE
Vivaldi update

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#118]

**Comment by onodera-punpun** [comment]
Vivaldi is closed source and I no longer use it so this might take a while. 😅

**Comment by rtlanceroad** [comment]
I am aware about that.

**Comment by rtlanceroad** [comment]
If it's hard to update, or you won't want to maintain it, we can just move it to orphan. I don't think anyone use it.

**Comment by rtlanceroad** [comment]
I just removed vivaldi from repo for several reasons:
```
- Non free.
- The package is very big and hard to provide a continuous update from us.
- Security-fixed and bug fixes are distributed as .deb or .rpm format, not in this source itself.
```
