### ISSUE TITLE
Audio stopped working in firefox-quantum 58

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#119]
Using ALSA, anyone else experiencing this?

**Comment by rtlanceroad** [comment]
I think you need to file a bug in the firefox forum and I find a bunch of people have ALSA issues with latest firefox/firefox developer edition.

**Comment by onodera-punpun** [comment]
Sadly they dropped ALSA support in 56 or 57 so I doubt they'll fix it. Nonetheless I'll look for patches.

**Comment by onodera-punpun** [comment]
Fixed in https://github.com/6c37/crux-ports/commit/4f6d57fad2bca4e950a7c668d75c052a72f48854

More info: https://github.com/i-rinat/apulse#firefox-58-tabs-crashing-when-trying-to-play-audio
