### ISSUE TITLE
mpd: Add "&& /usr/bin/mpc pause" to /etc/rc.d/mpd?

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#12]
This way music doesn't immediately start playing on boot: the "downside" is that we need to add mpc as a dependency.

**Comment by kori** [comment]
Music doesn't immediately start playing on boot, though.

Do you have a differing setup?

**Comment by KittyKatt** [comment]
Depends on if you stopped MPD the last time it was running or not. If you didn't, it's state still exists as "play", so it will play when started.

**Comment by kori** [comment]
It only does that when state_file is defined in your mpd.conf.
