### ISSUE TITLE
httpup REPO files are out of sync

### ISSUE THREAD

**Issue by mhoush** [6c37/crux-ports#127]
Greetings! Just opening this issue to report that the REPO files for crux-ports, crux-ports-git, and crux-ports-dropin are all out of sync. While git may be the primarily-preferred method of obtaining these repositories, the portdb uses httpup for them, so their data will be inaccurate there.

**Comment by rtlanceroad** [comment]
You are right. We suggest users to use git for instant updates/fixes. I just update REPO file periodically when I work full time on it. I hope portdb has a way of handling git changes. Thanks for letting us know.

**Comment by rtlanceroad** [comment]
track issue on #130
