### ISSUE TITLE
Blender 2.79b failed to build

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#128]
I got this issue when building blender 2.79b in VM:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/bmiintrin.h:104:1: error: inlining failed in call to always_inline 'unsigned int _tzcnt(unsigned int)' : target specific option mismatch: _tzcnt_u32(unsigned int __X)
 ```
That was called from `blender-2.79b/intern/cycles/util/util_simd.h:260:20`: line `return _tzcnt_u32(v);`.
I googled it and found that it sound like compiler target in WM doesn't support it.

**Comment by rtlanceroad** [comment]
@onodera-punpun Care to take a look at it?

**Comment by rtlanceroad** [comment]
`/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/bmiintrin.h` line 104:
```
_tzcnt_u32 (unsigned int __X) {
    return __builtin_ia32_tzcnt_u32 (__X);
}
```
It looks like it calls IA32's function which our gcc doesn't have a support.

**Comment by onodera-punpun** [comment]
What does VN (and WM) stand for here?

**Comment by onodera-punpun** [comment]
I got blender to build just fine.

**Comment by rtlanceroad** [comment]
Yes, virtual machine. I have to build the ports on a fresh system for general goods, therefore launching a virtual machine is better. please push the update.

**Comment by onodera-punpun** [comment]
I'll do when I'm home. Did you make any changes to the `Pkgfile` besides changing the version number

**Comment by rtlanceroad** [comment]
No. but there is something: 
```
rm -rf $PKG/usr/share/{doc,$name/${version%a}/scripts/addons/cycles/license}
```
Pay attention to the `${version%a}` , else license won't be removed. :)
