### ISSUE TITLE
tint2-svn package request

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#13]
I don't know this is the right place to request a package, but I think I should do. If someone feels uncomfortable about it, please close it.

Some of you guys may use tint2(0.11) in our official repo, but it's too old, and it was released on 2011 or before. Now as I can see, tint2 in svn has a new feature in it---launcher. More info about launcher can be seen in code.google.com/p/tint2 .

And in particular, I wanna mention something about the source url. You may say, it's in google code svn. Yes, I totally agree. But people, like me. from China or other countries. are very hard to access google code, even with proxy(openVPN/vpnc/ssh/shadowsocks/). So I guess this url (https://github.com/svn2github/Tint2) can be considered as a second choice. We can set a if statement anyway. If users failed to get that code, we can let user choose the github url.

**Comment by rtlanceroad** [comment]
@kori  @lainsce  :+1:    Thanks, you guys. I think I can close it now.

**Comment by kori** [comment]
No problem.

Sorry it took so long.
