### ISSUE TITLE
3.4 branch

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#130]
- [x] Create master branch
- [x] Create master branch for 6c37-git
- [x] Create master branch for 6c37-dropin
- [x] Remove `rust`
- [x] Check if all ports still compile
- [x] Update REPO
- [x] Mail crux team with new git info
- [x] Fix wiki, links etc
- [x] Update stuff in the cross repo

**Comment by onodera-punpun** [comment]
We should probably make the `3.4` branch `master` once it actually has been released, seeing how port github links now break every release.

**Comment by rtlanceroad** [comment]
Yeah, we need to fix sync file everytime a new release is out. Can we just rename `3.4` branch back to `master` branch  for not breaking github links?  If we do that, gcc ABI mismatch is the only serious issue for us because a ABI mismatch will gets linker error during package build. As far as I can see, updating 6.4.0 -> 7.3.0 won't get ABI change, so it's safe.

**Comment by onodera-punpun** [comment]
I'll be installing 3.4 today hopefully.

**Comment by onodera-punpun** [comment]
Changed to the `master` branch (we'll leave `3.3` for what it is?), removed `rust` since it is in `opt` now, we'll be keeping `firefox-quantum` I think, because it as a few nice `.mozconfig` options.

**Comment by rtlanceroad** [comment]
Great! Remember to email infrastructure team that we changed sync file to `master` branch and used a new link. :)

**Comment by onodera-punpun** [comment]
Thanks a lot, I'll mail the new files to the crux team tonight :)

**Comment by onodera-punpun** [comment]
Send a mail, closing this :)
