### ISSUE TITLE
3.2 branch: Move man pages to /usr/share/man

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#16]

**Comment by kori** [comment]
This is a bit more complicated than what could be done for the git ports, so let's work on this when 3.2 comes out, but not any earlier.

**Comment by rtlanceroad** [comment]
Wait for 3.2 final release or its rc stage(rc-1) release ?  :)

**Comment by kori** [comment]
Final release would be ideal.

**Comment by kori** [comment]
Done.

**Comment by kori** [comment]
Actually, whoops.
This could start getting work now.

**Comment by arcetera2** [comment]
Done (I think).
