### ISSUE TITLE
cargo: Move to crux-ports-git

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#18]
Since it's a nightly package I think it better to put it there.

**Comment by arianon** [comment]
You can always fetch the latest tag from [their GitHub page](https://github.com/rust-lang/cargo/releases/) :)

But in a perfect world, pkgutils would use multiple optional sources for the same package, for instance downloading the HEAD or the latest stable release using the same port/formula, a la [Homebrew](https://github.com/Homebrew/homebrew).

@kori please finish surt :disappointed:

**Comment by kori** [comment]
If no one's done this yet, it just means cargo isn't maintained anymore.

**Comment by lainsce** [comment]
`cargo` is still in high development, now it's version is equal to `rustc`

**Comment by kori** [comment]
I meant the port.

**Comment by kori** [comment]
Original comment fixed to reflect that.
