### ISSUE TITLE
blender 2.75a md5sum mismatch

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#19]
=======> ERROR: Md5sum mismatch found:
MISSING   7d04c789df8c74a5ce72677f1ceec314  blender-2.75a.tar.gz
NEW       ef4e1c9b36a64d7b85d938f69a908401  blender-2.75a.tar.gz

Also see http://download.blender.org/source/blender-2.75a.tar.gz.md5sum for confirmation of the correct md5sum.

**Comment by kori** [comment]
#20 nullifies the work done here.

**Comment by onodera-punpun** [comment]
For some reason blender changes their sources without changing the version number every once in a while, will update to 2.76.
