### ISSUE TITLE
Weechat: footprint error

### ISSUE THREAD

**Issue by kyubiko** [6c37/crux-ports#21]
With the current dependencies listed weechat will give a footprint error when installed even if all dependencies are installed. This is because lua is only listed as an optional dependency. I suggest we remove `-rwxr-xr-x root/root usr/lib/weechat/plugins/lua.so` from the footprint file. This will result in a NEW if it is built with lua support as opposed to a MISSING when without which I think is closer to the desired behaviour.

**Comment by onodera-punpun** [comment]
Should I do the same with `-rwxr-xr-x	root/root	usr/lib/weechat/plugins/python.so` and `-rwxr-xr-x	root/root	usr/lib/weechat/plugins/perl.so`?

**Comment by kyubiko** [comment]
I don't know, I was able to build it only having removed the line I quoted and that was on a freshly installed system. I python and perl got fetched in as the dependency of something else? Seeing as I have a freshy system to test on I'll give it a test once I get the time.

**Comment by onodera-punpun** [comment]
yeah perl gets provided by core so that should be installed anyways, I'll just remove lua for now.
