### ISSUE TITLE
openimageio fails to build

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#23]
Here's the buildlog: http://sprunge.us/MDje

Boost version is 1.59.0

**Comment by jmf** [comment]
Try rebuilding ilmbase and then build openimageio.
It worked for me after doing that.

**Comment by Wildefyr** [comment]
Builds fine for me.

**Comment by rmull** [comment]
Ended up rebuilding boost, ilmbase, and finally openexr before it worked for me. I've run into other build failures that were resolved by rebuilding the deps - this is a system that was updated from CRUX 3.1 -> 3.2 and there is apparently a bunch of stuff that isn't getting detected by revdep.
