### ISSUE TITLE
libbsd: Update 0.7.0 -> 0.8.0

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#26]
libbsd 0.8.0 was just released.

Source tarball:
  <http://libbsd.freedesktop.org/releases/libbsd-0.8.0.tar.xz>

GPG signature:
  <http://libbsd.freedesktop.org/releases/libbsd-0.8.0.tar.xz.asc>

**Comment by kori** [comment]
On it, thanks.

**Comment by kori** [comment]
Done, 83f1022
