### ISSUE TITLE
libbsd: Update 0.8.0 -> 0.8.1

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#27]
Release notes: This release fixes some general and portability build problems introduced in the last release. It also switches the COPYING file to the Debian machine readable format.

Source tarball:  http://libbsd.freedesktop.org/releases/libbsd-0.8.1.tar.xz
GPG signature: http://libbsd.freedesktop.org/releases/libbsd-0.8.1.tar.xz.asc

**Comment by ix** [comment]
Will do when I get home.

**Comment by ix** [comment]
Done.

**Comment by rmull** [comment]
I have an md5sum mismatch - looks like you changed the version number but not the md5sum.

=======> ERROR: Md5sum mismatch found:
MISSING   262bdd1aa3bee6066a8c9cb49bb6c584  libbsd-0.8.0.tar.xz
NEW       f3daff0283af6e30f25d68be2deac4ef  libbsd-0.8.1.tar.xz
=======> ERROR: Building '/usr/ports/6c37/libbsd/libbsd#0.8.1-1.pkg.tar.gz' failed.

**Comment by ix** [comment]
Will fix when I'm home.

**Comment by Wildefyr** [comment]
Hey wait a minute... that's what you said last time!

**Comment by rtlanceroad** [comment]
We can close it, see commit a6692200d63f6eb68e17bc8017ef9ed946253aa5 .
