### ISSUE TITLE
Move 3.2 branch to master.

### ISSUE THREAD

**Issue by ix** [6c37/crux-ports#30]
Most projects use master rather than a specialized branch. Don't see why we wouldn't.

**Comment by kori** [comment]
Transitional branches need to exist between versions, and old branches will get purged as the transitions are complete.
I don't see why not name the current branch after the current release.

**Comment by ix** [comment]
Got it.

**Comment by onodera-punpun** [comment]
Also, all of the official CRUX repo's use 3.0, 3.1, 3.2, etc. branches, the current version being the main branch.
