### ISSUE TITLE
Port clean ups: google-chrome, gconf

### ISSUE THREAD

**Issue by kori** [6c37/crux-ports#31]
Please run prtverify and remove the junk files.

**Comment by lainsce** [comment]
I already have run prtverify on each one before pushing.

**Comment by kori** [comment]
See these: 
`
ERROR  crux-ports/gconf ......... directory not allowed: usr/libexec/
ERROR  crux-ports/gconf ......... directory not allowed: usr/share/locale/
`

**Comment by ix** [comment]
If you do that Chrome crashes.

**Comment by Wildefyr** [comment]
Great reason not to use chrome then.

**Comment by ix** [comment]
It's not my port, and I don't use Chrome myself. Should we just pull it from the repositories? Lains has this port on their personal repository as well.

**Comment by rtlanceroad** [comment]
@lainsce Hi, glad to see google chrome works for me, but for me, it doesn't. I've tried prologics', it doesn't work either. So in this case, you can create a personal repo and self maintain it.

**Comment by onodera-punpun** [comment]
Why remove it though, we have some more "improper" ports like some install in /opt.

**Comment by kori** [comment]
No need for removal, there's just a need to check which files can be removed.

**Comment by lainsce** [comment]
Let's test _everything_

**Comment by rtlanceroad** [comment]
I am in favor of removing it from repo. The reasons are as following:
1. This chrome doesn't work(at least my case). If a browser can't browse, why we maintain it?
2. Chrome is closed cource. In order to use it, one needs to extract deb/rpm, that's not right....
3. There is alternative chromium in /opt, it WORKS great as it is. 
4. maybe other  reasons here.

**Comment by kori** [comment]
1. It works here, and we can fix whatever doesn't work.
2 and 3: Chrome can use Netflix.

**Comment by Wildefyr** [comment]
So can chromium. You just have to enable/install the drm html5 module.

**Comment by lainsce** [comment]
I've decided that you guys can remove those ports since I've done a git-port-driver-thingy (Seriously, what's the name for the file on /etc/ports?) for my repo.

**Comment by kori** [comment]
Well, what's the status on this issue?
Should we close it then?

**Comment by ix** [comment]
Since this has been opened for a while and it likely can't be fixed I'm closing this.
