### ISSUE TITLE
zathura(0.3.4) can't compile

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#32]
The build log is as following:

┌────[lee@sakura]───────[07:15:35]───────[~/test/crux-ports|3.2]───────────────────────────────────────────────────────────────────────────────────────────────────────
└──> sudo prt-get depinst zathura
prt-get: installing /home/lee/test/crux-ports/zathura
=======> Building '/home/lee/test/crux-ports/zathura/zathura#0.3.4-1.pkg.tar.gz'.
bsdtar -p -o -C /home/lee/test/crux-ports/zathura/work/src -xf /home/lee/test/crux-ports/zathura/zathura-0.3.4.tar.gz
+ build
+ cd zathura-0.3.4
+ make
zathura build options:
CFLAGS  = -O2 -march=x86-64 -pipe -std=c11 -pedantic -Wall -Wno-format-zero-length -Wextra -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
LIBS    = -lgirara-gtk3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgthread-2.0 -pthread -lglib-2.0 -lgmodule-2.0 -pthread -lglib-2.0 -lglib-2.0 -lpthread -lm -lsqlite3 -lmagic
DFLAGS  = -g
CC      = cc
 [CC] zathura/adjustment.c 
 [CC] zathura/jumplist.c 
 [CC] zathura/types.c 
 [CC] zathura/synctex.c 
 [CC] zathura/callbacks.c 
 [CC] zathura/marks.c 
 [CC] zathura/content-type.c 
 [CC] zathura/commands.c 
 [CC] zathura/config.c 
 [CC] zathura/database-plain.c 
 [CC] zathura/database.c 
 [CC] zathura/bookmarks.c 
 [CC] zathura/page-widget.c 
 [CC] zathura/main.c 
zathura/main.c: In function 'init_zathura':
zathura/main.c:89:11: warning: unused parameter 'synctex_editor' [-Wunused-parameter]
     char* synctex_editor, Window embed)
           ^
zathura/main.c: In function 'main':
zathura/main.c:254:26: error: 'synctex_editor' undeclared (first use in this function)
       plugin_path, argv, synctex_editor, embed);
                          ^
zathura/main.c:254:26: note: each undeclared identifier is reported only once for each function it appears in
Makefile:103: recipe for target 'build/release/zathura/main.o' failed
make: *** [build/release/zathura/main.o] Error 1
=======> ERROR: Building '/home/lee/test/crux-ports/zathura/zathura#0.3.4-1.pkg.tar.gz' failed.
prt-get: error while install

-- Packages where install failed
zathura

You are welcome to debug this one. That function indeed first appears in $BUILD_DIRECTORY/zathura/main.c. I've no idea how to deal with it.

**Comment by rtlanceroad** [comment]
For better review:  http://paste.ubuntu.com/14278801/

**Comment by ix** [comment]
Is this something we can actually fix? It could be a problem with upstream.

**Comment by rtlanceroad** [comment]
We can help to fix it : )

**Comment by rtlanceroad** [comment]
According to the README in zathura source directory, synctex_editor and synctex.h need texlive to be installed. Although texlive is in /opt, but texlive source tarball is 1.8g... that's huge, beyond my imagination. If someone interested, please help to test.

**Comment by rtlanceroad** [comment]
Actually it's not fixed, it's skipped.... see commit https://github.com/6c37/crux-ports/commit/aad4f622e1cc0df2ad6620750f9904734ae3cf73  According to build instruction in source code, texlive is optial dep, but BUILD highly relies on it(kind of hard coded).... Since nobody likes to build texlive, we skip that. The patch is borrowed from voidlinux(https://github.com/voidlinux/void-packages/blob/e4756d3f8da4b0372a7c2d55473fc3161415e09c/srcpkgs/zathura/patches/fix_build_without_synctex.patch).
