### ISSUE TITLE
httpup and the portdb.

### ISSUE THREAD

**Issue by ix** [6c37/crux-ports#33]
6c37 is yet another CRUX repo with quality and exclusive ports. It however, due to it being exclusively git, does not qualify for the portdb.

We could make 6c37 an httpup repository while still using GitHub (example: https://github.com/baguette/crux-ports), which allows us to use httpup for the portdb and for legacy usage but still recommending the git driver.

This would also add running `httpup-repgen` in the typical fetch-merge-mkport-build-add-commit-push cycle.

Now the question is, should we do it?

**Comment by Wildefyr** [comment]
I vote yee.

**Comment by rtlanceroad** [comment]
Yes, definitely. It's never a bad idea to give another solution. : )

**Comment by neeasade** [comment]
+1

**Comment by ix** [comment]
There's no objections here; should we go ahead and do it?

**Comment by kori** [comment]
Aye. But someone needs to make the httpup-repgen thing as a git hook or something.

**Comment by ix** [comment]
Pretty sure that's something that needs to be done on the client, not server.

**Comment by kori** [comment]
Sure. I'm saying that someone needs to figure that out and then put up a guide on the wiki or something.

**Comment by Wildefyr** [comment]
Where is the plan to host it? I don't mind doing it though.

**Comment by ix** [comment]
GitHub. It's doable.

**Comment by ix** [comment]
I'm going to do this now. Give me a minute.

**Comment by ix** [comment]
I've edited the wiki page for "Commit standards" so people run httpup-repgen before they commit, and I've set up the repo so httpup works.
