### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by Wildefyr** [6c37/crux-ports#34]
Want to clarify what the port repositories are for passersby. Also we should probably ship the repository's .git file that goes in /etc/ports. Any nays?

**Comment by ix** [comment]
I'm for the README, but as for the .git file in the actual repo, I say no. It's in cross and it should stay in cross.

**Comment by onodera-punpun** [comment]
Well we already have the wiki. The thing is, if we add a README it will also be pulled in by ports -u

**Comment by rtlanceroad** [comment]
Vote for NO this time.

**Comment by Wildefyr** [comment]
I don't think having it pulled in by ports -u is a massive deal at all. As for the wiki, I think it's definitely not as obvious as a README.md would be.

**Comment by rtlanceroad** [comment]
Seriously, README should not appear in a port repo, that's kind of potential agreement we all obey. For passersby, I am assuming the following situations:  1. They are linux newbies, randomly see 6c37, arise interests, then dig into our thing. and find a word, called "CRUX". just like everybody, after googling for a while, they start a hard journey with it. 2. They are experienced linux users, find 6c37 and use it directly without any problems(wrt the whole project, not ports themself). Both situations don't need a README in our repo and git repo. <---- That's the idea coming out at the time of writing. : )

**Comment by Wildefyr** [comment]
Sure. An eager party would do that. What I am saying is just to add a title and brief couple of sentences. Nothing more really.

**Comment by ix** [comment]
Perhaps we could add the ability to exclude files in the git driver? This would also be useful if we implement httpup.

**Comment by kori** [comment]
@ix That's a big no for me.

@Wildefyr What should the readme contain?

**Comment by Wildefyr** [comment]
Gonna close this I think, I am not quite sure what it would contain really other than a brief description and it seems people are split over this.
