### ISSUE TITLE
Python 3.5.1 - broken footprint

### ISSUE THREAD

**Issue by jmf** [6c37/crux-ports#39]
Python 3.5.1 reports missing files at footprint check.
Possible introduction of the issue in ef23f1f
```
MISSING   drwxr-xr-x      root/root       usr/lib/python3.5/config-3.5m/__pycache__/
MISSING   -rw-r--r--      root/root       usr/lib/python3.5/config-3.5m/__pycache__/python-config.cpython-35.opt-1.pyc
MISSING   -rw-r--r--      root/root       usr/lib/python3.5/config-3.5m/__pycache__/python-config.cpython-35.opt-2.pyc
MISSING   -rw-r--r--      root/root       usr/lib/python3.5/config-3.5m/__pycache__/python-config.cpython-35.pyc
```

**Comment by onodera-punpun** [comment]
I just build this myself and didn't get the footprint error, are you missing some dependency by chance?

**Comment by rmull** [comment]
@jmf, can we get an update or any more information on this? I do not get this footprint error either. Perhaps try removing and reinstalling the port to see if there is any difference?

**Comment by rtlanceroad** [comment]
@jmf fresh install on Virtualbox doesn't give me footprint error, for the time being, I close it.
