### ISSUE TITLE
luajit - broken footprint

### ISSUE THREAD

**Issue by tudurom** [6c37/crux-ports#45]
missing usr/lib/luajit-5.1.so and usr/lib/luajit-5.1.so.2

**Comment by onodera-punpun** [comment]
Hmm, I'm not getting that error? Are you using some weird build options or something?

**Comment by wildefyr** [comment]
No footprint mismatch here either

**Comment by tudurom** [comment]
I just run `prt-get depinst luajit`, nothing more.

**Comment by wildefyr** [comment]
You can use `prt-get deptins luajit -uf` to update the footprint locally.

**Comment by tudurom** [comment]
I know, but I am a good guy and I reported that

**Comment by onodera-punpun** [comment]
Are you only missing usr/lib/luajit-5.1.so and usr/lib/luajit-5.1.so.2? Are there any NEW files?

**Comment by tudurom** [comment]
no new files. just missing those two

**Comment by onodera-punpun** [comment]
After installing the port with -if or -uf can you do a `~ ls /usr/lib | grep luajit-5.1`?

**Comment by tudurom** [comment]
```
libluajit-5.1.a
libluajit-5.1.so.2
libluajit-5.1.so.2.0.4
