### ISSUE TITLE
Steam: constant runtime issues.

### ISSUE THREAD

**Issue by wildefyr** [6c37/crux-ports#47]
https://p.iotek.org/mca

As an example, see above. Removing the user's .local/share/Steam seems to help for awhile, but then invariably breaks again. Sometimes it will fail to load entirely.

**Comment by onodera-punpun** [comment]
Should this issue be closed now (see #48)? Anyways I remember my steam crashing only AFTER the first launch because I was missing some dependency (this was long ago, so I forgot which dep).

**Comment by wildefyr** [comment]
Agreed. We should report further problems to the package maintainer for the port in the contrib repo.
