### ISSUE TITLE
Remove libressl patches

### ISSUE THREAD

**Issue by wildefyr** [6c37/crux-ports#49]
Really, the libressl patch should be maintained in a user's port repo if they want that. No need to not follow upstream.

**Comment by ix** [comment]
We provide LibreSSL, so it's pretty important.

**Comment by rmull** [comment]
The original reason I used this repo was to use libressl. I had at one point contributed some Ruby patches to enable building against libressl (now no longer necessary). IMO providing build fixes for software that does not build against libressl is in the original spirit of the repo and should be maintained until upstream resolves the issues.

-1 from me.

**Comment by onodera-punpun** [comment]
I feel like this could be a slippery slope, what if we add musl or some other replacement, do all ports need patches for that software as well?

I'm working on called prtpatch which could be used for cases like this, but it needs some more refinement. 

+-0 from me :).

**Comment by wildefyr** [comment]
The reason I bring this up is if you don't want to use libressl, the patches feel dirty and unneeded. I'm not against providing libressl but if you need to patch the software in this manner for it to work, I don't think it's really worth maintaining it here.

**Comment by ix** [comment]
Howso? They work on both OpenSSL and LibreSSL.

**Comment by rmull** [comment]
Which ports have libressl patches at the moment? I see socat and nodejs, any others?

**Comment by kori** [comment]
The original reason LibreSSL patches were provided here is that software in core/contrib/opt didn't compile against LibreSSL, so we provided an overlay with patched software that would compile against LibreSSL (And OpenSSL)

**Comment by kori** [comment]
Closing as dropin exists now.
