### ISSUE TITLE
mpv depends on packages in contrib

### ISSUE THREAD

**Issue by kyubiko** [6c37/crux-ports#5]
Contrib is not enabled by default, so the user will have to add it to use our mpv port. This seems to defeat the point of having an mpv port, as if the user has to add contrib anyway they may as well use the existing mpv port in contrib. The only difference between ours and the contrib port being that ours is a git checkout. The way I see it there are 2 alternatives to the current state; removing our mpv port, or adding those dependencies to our collection.

**Comment by kori** [comment]
`contrib` is invariably necessary if you're looking for a proper desktop system.

It contains a bunch of dependencies for a bunch of ports.

Choosing between our port and mpv from contrib is choosing between following upstream and stable, respectively.

**Comment by kyubiko** [comment]
That makes sense, closing.
