### ISSUE TITLE
There's a couple of duplicated ports between 6c37 and 6c37-git

### ISSUE THREAD

**Issue by wildefyr** [6c37/crux-ports#50]
We should decide if we want the git version or stable version of the following packages due to maintenance costs:
- fish
- lemonbar

Personally I am in favour of the git version for these.

**Comment by onodera-punpun** [comment]
I already deleted the fish port once, but someone was using it so I readded it. The whole point of splitting 6c37 into 6c37 and 6c37-git was to avoid collisions and make it possible to maintain both a release and git version.

**Comment by rtlanceroad** [comment]
I am the guy using fish, :) You guys can delete one and leave one there, I don't care about which one you delete, but keep one there :)

**Comment by rmull** [comment]
I choose not to use the git ports because it's a little too bleeding edge for me. While none of the ports I use from crux-ports have been deleted because of a duplicate in crux-ports-git, I would prefer if they were maintained separately, and it should be implied that users of a non-git port can feel free to report any version bump needs should they arise.

**Comment by rtlanceroad** [comment]
While after a _long_ time, the answer is quite clear to me: both packages should be kept on stable repo. reasons are followings:

1. Both packages provides cycle release tarball with bug fixes, which means devs hope users to use 
    stable releases for a production system.
2. Git means we are in a middle of development, and it may contains critical bugs. It's good for devs  
     to participate in software development, but _**not**_ for users.
3. I still dont think people want to enable 2 repos at the same time, which give a mess on system.

@onodera-punpun is working hard on `git` repo,  he maybe have some thoughts on this.

**Comment by kori** [comment]
Closing.
