### ISSUE TITLE
nodejs 4.2.6 -> 4.4.4, needs updates to fix-libressl.patch

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#56]
I attempted a simple version bump, but the patch doesn't apply cleanly. @onodera-punpun since you're the one who added this port, maybe see about massaging the patch to apply against 4.4.4. I don't use nodejs, so no pressure.

**Comment by onodera-punpun** [comment]
I got the patch from void, from what I remember they updated to a more recent nodejs that uses some statically linked openssh. I'll check if they have created any new libressl patches as of yet, or maybe alpine linux has.

**Comment by rmull** [comment]
Closing this because it looks like nodejs was updated, thank you.
