### ISSUE TITLE
libbsd: Drop this port, it's now in contrib

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#57]
libbsd was recently introduced to contrib, so we should drop this port. I didn't want to do it without presenting a notification.

**Comment by onodera-punpun** [comment]
Aaaand it it has beeen removed from contrib

**Comment by rmull** [comment]
Are you sure? It seems to still be there: https://crux.nu/gitweb/?p=ports/contrib.git;a=shortlog;h=refs/heads/3.2

**Comment by onodera-punpun** [comment]
Oh you are right, I was searching for libsd lol.
