### ISSUE TITLE
chicken 4.11.0 needs updating

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#59]
@onodera-punpun Since you are on musl, please ^

**Comment by onodera-punpun** [comment]
Actually kori used musl and chicken. Since he left what do you think about creating a crux-ports-oprhaned repo?

**Comment by kori** [comment]
I didn't leave!!!
But yeah, creating such a repo is fine. I'm going to do it.

**Comment by kori** [comment]
Done.
