### ISSUE TITLE
libconfig 1.6 failed to build

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#63]

**Comment by onodera-punpun** [comment]
yeah, there is a bug report on thir github. They have released 1.6 forever now, but it's STILL not fixed.

IMO we should drop libconfig, the only package that depends on it is compton for config files (without libconfig you just need to configure compton via flags).

**Comment by rtlanceroad** [comment]
The current fix is remove lib/scanner.c. see commit https://github.com/6c37/crux-ports/commit/4a927d901cb8f36a4fca358f99ad3ab52362b8aa  hopefully 1.6.1 fix this. I'll close it.
