### ISSUE TITLE
easytag 2.4.2 is newer version, but failed to build.

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#65]

**Comment by onodera-punpun** [comment]
gtk3 is no longer supported since 2.something, there is an (almost,  I think) up to date easytag-gtk3 in oprhaned.

**Comment by rtlanceroad** [comment]
the commit 350ce99fc0bb7f67d2e03ebc94a1efe41911ea18 fixed this. The previous build failure is because someone writes libid3tag as lib3tag, which causes texinfo: undefined reference _xxx_. Sorry about this,

**Comment by rtlanceroad** [comment]
I'll look at our orphan repo if this repo is kinda done.

**Comment by onodera-punpun** [comment]
easytag 2.4.2 still doesn't build without gtk3, please revert to the 2.2.6 branch :)

**Comment by rtlanceroad** [comment]
you are right.

http://img.vim-cn.com/cf/8cc134aee2d308c795b08ab125c4474d677573.png

**Comment by rtlanceroad** [comment]
fixed by commit edf7090e329f28e646c2d06137c7918f64fdf28f
