### ISSUE TITLE
Gvfs-dockbook.xsl Failed to Load Entity

### ISSUE THREAD

**Issue by speden** [6c37/crux-ports#66]
I'm trying to install gvfs and keep getting this error msg:
`make[2]: Entering directory '/usr/ports/6c37/gvfs/work/src/gvfs-1.28.2/man'
  GEN      gvfs-cat.1
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make[2]: *** [Makefile:713: gvfs-cat.1] Error 4
make[2]: Leaving directory '/usr/ports/6c37/gvfs/work/src/gvfs-1.28.2/man'
make[1]: *** [Makefile:532: all-recursive] Error 1
make[1]: Leaving directory '/usr/ports/6c37/gvfs/work/src/gvfs-1.28.2'
make: *** [Makefile:464: all] Error 2
=======> ERROR: Building '/usr/ports/6c37/gvfs/gvfs#1.28.2-1.pkg.tar.gz' failed.
prt-get: error while install

-- Packages where install failed
gvfs

-- Packages installed
polkit
udisks2
`
I've tried adding "enable runscripts in /etc/prt-get.conf" to , sadly it still didn't help with the gvfs docbook.xsl issue.

**Comment by rtlanceroad** [comment]
@speden Hi, it's issue with docbook-xml and docbook-xsl.
you can do following to fix it:
# prt-get update -fr docbook-xml docbook-xsl
# prt-get depinst gvfs

**Comment by rtlanceroad** [comment]
You can also uncomment line in /etc/prt-get.conf to run pre- and post- scripts:
runscripts yes # (no | yes)

it should be safe even with 3rd party repo.

**Comment by speden** [comment]
rtlanceroad, thank you.  "prt-get update -fr docbook-xml docbook-xsl --install-scripts" did the trick, it finished compiling and installed.  I had to update the .footprint also.

I did switch the "runscripts yes (no | yes) option before and it still didn't work at that point.

Thanks again.

**Comment by rtlanceroad** [comment]
great :)
