### ISSUE TITLE
mpd 0.19.18 failed to compile because current ffmpeg 3.1.1 API breaks it.

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#68]

**Comment by rtlanceroad** [comment]
Also in `contrib`, there is also a pkg __mpd__ . @onodera-punpun any idea about it?

**Comment by onodera-punpun** [comment]
the mpd in contrilb *still* uses /usr/man as a port-dir which kinda annoys me, and is the reason I kept the 6c37 mpd port.

As for building 0.19.18, it just works for me (with ffmpeg 3.1.1)...

**Comment by rtlanceroad** [comment]
okay, I'll close it.

**Comment by onodera-punpun** [comment]
does it build for you now, or..?

**Comment by rtlanceroad** [comment]
actually not. but good to see it builds for you.

**Comment by onodera-punpun** [comment]
any errors?

**Comment by rtlanceroad** [comment]
This is screenshot from vm test, a lot of libavcodec.so undefined reference:
![screenshot-2016-08-09 13 25 23](https://cloud.githubusercontent.com/assets/7656607/17505625/fe2a1d76-5e34-11e6-9502-c64f91a64c76.png)

**Comment by rtlanceroad** [comment]
sorry, problem is in my part, rebuilding ffmpeg then mpd works for me.
