### ISSUE TITLE
freetype has 2.7 released, hopefully there will be new patches for freetype-ui

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#69]

**Comment by onodera-punpun** [comment]
Heh, I'm still using some forked patches for 2.6.3, see https://github.com/NixOS/nixpkgs/pull/17846

**Comment by rtlanceroad** [comment]
Maybe [fontconfig-ultimate](https://github.com/bohoomil/fontconfig-ultimate) and [infinality_bundle](https://github.com/archfan/infinality_bundle) will deliver new patches if freetype 2.7 is avaliable in repo.

**Comment by rtlanceroad** [comment]
Thanks.
