### ISSUE TITLE
vim-x11?

### ISSUE THREAD

**Issue by kori** [6c37/crux-ports#7]
What's the difference between 6c37/vim-x11 and opt/gvim?

**Comment by onodera-punpun** [comment]
This is compiled with X11 support, but without the GUI. The key difference between this and vim in the repos is that Xorg clipboards are supported ("* and "+ registers). GUI is not compiled in. (It's only about 0.15 MB smaller than gvim, and is specifically for people who want X11 clipboard support but not the GUI for some reason).

**Comment by kori** [comment]
Fair enough.
