### ISSUE TITLE
Switch back to `Nice to have` instead of `Optional`

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#70]
It's the standard, and people might use Nice to have in scripts. Thoughts?

**Comment by wildefyr** [comment]
Really depends on the software, IMO, as some stuff might be needed at compile time. I think optional describes it just fine though.

**Comment by onodera-punpun** [comment]
I mean, rename `# Optional:.*` to `# Nice to have:.*`, this is the standard CRUX uses.

**Comment by wildefyr** [comment]
I wasn't aware of the switch, in that case, go for it!

**Comment by rtlanceroad** [comment]
+1

**Comment by onodera-punpun** [comment]
Ok it seems I like I was wrong and it isn't actually a CRUX standard I guess:

https://crux.nu/Main/Handbook3-2#ntoc28

```
/usr/ports/opt cat */Pkgfile  | grep Optional:
# Optional: ffmpeg speex jack libsamplerate
# Optional:	pygobject dbus-python sox gst-plugins-base-compat
# Optional: clang
# Optional:	ffmpeg alsa-lib cups directfb neon pulseaudio
# Optional: glade vala
# Optional: enchant libcanberra
# Optional: gobject-introspection
# Optional:	libsamplerate bluez avahi sbc orc lirc pyqt4
# Optional:	cups
# Optional: boost
# Optional:	python
/usr/ports/opt cat */Pkgfile  | grep Nice to have:
grep: to: No such file or directory
grep: have:: No such file or directory
/usr/ports/opt cat */Pkgfile  | grep 'Nice to have:'
# Nice to have: alsa-lib, flac, libao, libid3tag, libmad, libmodplug, libmpcdec, libvorbis
# Nice to have: libsdl
# Nice to have: gimp-print, libsdl, ghostscript, librsvg, libmng
# Nice to have: tk
# Nice to have: i2c-tools
# Nice to have: libsdl, libjpeg-turbo, libpng, lame, zlib, libogg, libvorbis, cdparanoia, win32-essential-codecs, faac, x264, libdvdnav, libdca
# Nice to have: pinentry-gtk2 pinentry-qt4
# Nice to have: libseccomp libiscsi libusb usbredir spice
# Nice to have: libseccomp libiscsi libusb usbredir spice
# Nice to have: gdb
```

Anyways imo it *should* be, for easy of use with scripts and programs that parse Pkgfiles.

Not sure which one to go with now.

**Comment by rtlanceroad** [comment]
I think it doesn't *really* matter, it's just a string whick makes prt-get tracks dependency easier. as we know, those dependencies are only installed if you look at Pkgfile *carefully*, so it's just kinda `label`.  :)

**Comment by rtlanceroad** [comment]
As i mentioned before, this is just a _LABEL_ of sorting optional dependecies for supporting optional software features, it _really_ doesn't matter. So I close this for now.
