### ISSUE TITLE
xorg-libxkbcommon: footprint mismatch when doxygen is not present

### ISSUE THREAD

**Issue by muphil** [6c37/crux-ports#72]
fix:
	./configure --prefix=/usr --disable-docs
	rm .footprint
	pkgmk

**Comment by rtlanceroad** [comment]
Thanks for reporting. If you unpack xorg-libxkbcommon somewhere and run `./configure --help | grep doxygen`, you will find:

```
--with-doxygen          Use doxygen to regenerate documentation (default: auto)
```
That's the reason why footprint mismatch. You are right, either pass `--disable-docs` to prevent doc from being regenerated or pass `--without-doxygen`. Both should work.

**Comment by rtlanceroad** [comment]
[This](140703915e303326403977ea982d870ba13ca459) should fix it.

**Comment by muphil** [comment]
Thank you.  I think it's better to run `httpup-repgen .` before every commits and pushes to make sure people using httpup be able to receive updated version of ports. 
I think add that command to .git/hooks/pre-commit should do the trick (not veified).

**Comment by rtlanceroad** [comment]
I use git drivers rather than httpup, but yes, @onodera-punpun please? :)
