### ISSUE TITLE
python3-setuptools: change source to remove `date` in file names

### ISSUE THREAD

**Issue by muphil** [6c37/crux-ports#73]
See the commit history of this port, some files have `date` in their names, and it breaks constantly (footprint mismatch). I've verified that changing the source to https://pypi.python.org/pypi/setuptools (here at the bottom)  fixes this issue, for the newest version currently, it should be:  https://pypi.python.org/packages/72/e1/741cd8c4825e58119481d8be4254c9cd133db50876b159cdf8cbd253fbb3/setuptools-27.3.0.tar.gz
They have different build presets in setuptools-$version/setup.cfg:
The source from github have tag_date=1, and I think that's the source of the issue.

**Comment by rtlanceroad** [comment]
Thanks again. [This](beb0a98f0d79c3d215dcc9eb1bbdb047e7c65266) should fix it.
