### ISSUE TITLE
gtk2 has been updated, but gtk-ahoka's patches hunk failed.

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#74]

**Comment by rtlanceroad** [comment]
Just for reminding.

**Comment by onodera-punpun** [comment]
I already notified ahoka :)

https://gist.github.com/ahodesuka/01213036b58e510dc074#gistcomment-1882653

**Comment by rtlanceroad** [comment]
Great.

**Comment by kori** [comment]
Closing, port moved to dropin.
