### ISSUE TITLE
Blender installs into wrong directories

### ISSUE THREAD

**Issue by jmf** [6c37/crux-ports#75]
According to the footprint, blender installs into some very odd places.
The executable is installed under /usr/blender instead of /usr/bin/blender, data under /usr/2.78 instead somewhere under /usr/share.

**Comment by rtlanceroad** [comment]
Whoops, totally my fault. I'll check it further.

**Comment by onodera-punpun** [comment]
@rtlanceroad from the quick look I had at it the portability flag seems to be the most(only?) likely flag that caused thiis

**Comment by rtlanceroad** [comment]
@onodera-punpun  I guess no. From what I see from CMakeLists.txt, it's because they force install to `EXECUTABLE_OUTPUT_DIR` if `CMAKE_BINARY_DIR` is not set. I am on the half way. if I am right, I'll push it.

**Comment by rtlanceroad** [comment]
We dont want a portable blender. :)

**Comment by rtlanceroad** [comment]
Well my guess is not right.

**Comment by rtlanceroad** [comment]
Thanks for pointing out from @onodera-punpun about portable, commit https://github.com/6c37/crux-ports/commit/ad29aa83823878e629c0c5379453001b35e6bd55 should fix this.
