### ISSUE TITLE
firefox-gtk2 needs updating

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#81]
As titled, the 50.1.0 includes a lot of security fixes, but access to mozilla http/ftp  is extremely slow, I can't even download the source.
@onodera-punpun would you update it?

**Comment by onodera-punpun** [comment]
So I've been trying to compile this all week, but my gcc *keeps* segfaulting, sorry

**Comment by rtlanceroad** [comment]
no problem, I'll take this over.

**Comment by rtlanceroad** [comment]
I'v updated it by commit 3598090b57f48e869f98f122eb4368653294cc39 . It works fine here.

**Comment by onodera-punpun** [comment]
Thanks!
