### ISSUE TITLE
Get ready for CRUX 3.3

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#82]
## General changes:

- [x] Add 3.3 branch
- [x] Add COPYING _(optional, I like consistency with the official repos though)_
- [x] Add COPYRIGHT _(optional, I like consistency with the official repos though)_
- [x] Use .signature
- [x] Make 3.3 the default branch

## Port specific changes:

- [x] Update `p5-text-aspell` footprint (needed because of updated `core/perl` version)

The fourth item in the list will take some research and discussion on how to handle the keys, so @rtlanceroad, @rmull, etc. hit me up in #6c37 or in this issue~

**Comment by rtlanceroad** [comment]
- I think we need to wait for 3.3 branch a while, until at least 3.3 -r1 iso released, although I see 3.3 mirror already roll out.
- COPYING and COPYRIGHT are yes, quite optional.
- 3.3 signature enhances the repo security, that's good, we need to imigrate.

**Comment by onodera-punpun** [comment]
The rc-1 iso is hosted here: https://crux.ninja/crux/

**Comment by kori** [comment]
I'm rejoining the team once 3.3 drops.

**Comment by kori** [comment]
By the way, we should probably license our ports under ISC, no big deal, though.

**Comment by onodera-punpun** [comment]
I like GPLv3, muh freedom.

**Comment by kori** [comment]
Unfortunately I ran into complications and won't be able to rejoin the team at this moment.

**Comment by rtlanceroad** [comment]
Well you are the project lead and we need you to send our private repo keys,

**Comment by rtlanceroad** [comment]
You could set up an virtual machine and generate key pair ;)

**Comment by kori** [comment]
Just to leave this documented, project leadership was delegated to onodera a while ago.

**Comment by onodera-punpun** [comment]
Done :)
