### ISSUE TITLE
rustc: won't build using sudo

### ISSUE THREAD

**Issue by maraku** [6c37/crux-ports#84]
rust doesn't build via sudo, as @onodera-punpun pointed out. just wanted to say that it builds fine using fakeroot in a writable directory as a normal user. should a readme be added to let users know about the problem until a new rust version is released with a fix?

**Comment by rtlanceroad** [comment]
@maraku You are right. Our Pkgfile will automatically download stage0 to move it to /tmp during build,so you know /tmp is owned by root, therefore sudo is not sufficient and we need real root to build it. Yes, I'll add a README  to mention it. Thanks for noticing us :)

**Comment by rtlanceroad** [comment]
I think commit bccc47a9b57faed26feeba2d761ac413884e250f fixed it.
