### ISSUE TITLE
python3-setuptools 34.0.1 needs fixing

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#85]
As we can see from commits https://github.com/pypa/setuptools/commit/089cdeb489a0fa94d11b7307b54210ef9aa40511 and https://github.com/pypa/setuptools/commit/336a065df01a4b409f57809a668208d666010a62, they introduced a lot of python dependencies for it. and more interesting thing is, `python3-pip` needs `python3-setuptools` building first, meanwhile `python3-setuptools` 34.0.1 now needs `python3-pip`, a circle dependency just happened.

**Comment by rtlanceroad** [comment]
This is what I can come up with. I mixed prt-get with pip3. Feel free to revert and go with other idea.

**Comment by dlcusa** [comment]
Does this introduce a Depends On: python3-pip for run-time or merely build-time?  Is python3-pip no longer necessary to build python3-setuptools once python3-setuptools has been upgraded to 34.1?

**Comment by dlcusa** [comment]
Please reopen this issue.  My update after installing `6c37/python3-pip 9.0.1-1` with `6c37/python3-setuptools 34.1.0-1` and `contrib/six 1.10.0-1` installed but no `python3-six` installed failed with the following final messages:
```
writing manifest file 'setuptools.egg-info/SOURCES.txt'
Regenerating egg_info
...and again.
+ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/usr/ports/work/python3-setuptools/src/setuptools-34.1.0/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ModuleNotFoundError: No module named 'six'
=======> ERROR: Building '/usr/ports/6c37/python3-setuptools/pkgsb3/python3-setuptools#34.1.0-1.pkg.tar.gz' failed.
```

Is `python3-six` also needed to update `python3-setuptools`?  If so, is it only needed for the build or is there a run-time depends, as well?

**Comment by dlcusa** [comment]
Well, I did install `python3-six` and tried again, getting:
```
-rw-r--r-- 1 root root 1.8K Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-setuptools.port.tar.bz2
-rw-r--r-- 1 root root    0 Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.alog
-rw-r--r-- 1 root root  947 Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.diffs
-rw-r--r-- 1 root root  13K Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.env.bz2
-rw-r--r-- 1 root root 1.3K Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.log.bz2
-rw-r--r-- 1 root root  230 Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.plog
-rw-r--r-- 1 root root  821 Jan 30 02:49 /var/log/pkgbuild/_/00031/03/python3-six.port.tar.bz2
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/usr/ports/work/python3-setuptools/src/setuptools-34.1.0/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/ports/work/python3-setuptools/src/setuptools-34.1.0/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/ports/work/python3-setuptools/src/setuptools-34.1.0/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
=======> ERROR: Building '/usr/ports/6c37/python3-setuptools/pkgsb3/python3-setuptools#34.1.0-1.pkg.tar.gz' failed.
```
I do have the module `/var/lib/pkg/db` thinks I should:
```
# ls -lahd /`grep packaging\\\.py\$ /var/lib/pkg/db`
-rw-r--r-- 1 root root 2.1K Nov  6 18:49 /usr/lib/python3.6/site-packages/pip/utils/packaging.py
```
I am uncertain what else my system lacks, as there are several other possibilities according to prt-cache fsearch.

**Comment by rtlanceroad** [comment]
> Does this introduce a Depends On: python3-pip for run-time or merely build-time?
Yes, `python3-pip` is needed to build `python3-setuptools` 34.0.1 and later version. But for 33.1.1 or before, `python3-pip` is not needed.

> Is python3-pip no longer necessary to build python3-setuptools once python3-setuptools has been upgraded to 34.1?
No. on the contrary, `python3-pip` is a hard dependency for building `python3-setuptools`, because devs use `import pip` in their bootstrap.py. Also there is a [pre-install](https://github.com/6c37/crux-ports/blob/3.2/python3-setuptools/pre-install) for `python3-seuptools` which uses `python3-pip` to install extra dependencies.
```
#!/bin/sh

pip3 install -U packaging appdirs
```

> My update after installing 6c37/python3-pip 9.0.1-1 with 6c37/python3-setuptools 32.3.1-1 and contrib/six 1.10.0-1 installed but no python3-six installed failed with the following final messages:
`contrib/six 1.10.0-1` is for python2, for python3, please install `6c37/python3-six`.

> Is python3-six also needed to update python3-setuptools? If so, is it only needed for the build or is there a run-time depends, as well?
Looks so for build dep, see https://github.com/pypa/setuptools/blob/master/setup.py#L167 they use `six` as a install_require. If needed, please install `6c37/python3-six` by seperate.

> Well, I did install python3-six and tried again, getting:
That's because you dont execute pre-install scripts I mentioned before. run this:
```
prt-get depinst python3-setuptools --install-scripts
```
or

in prt-get.conf, there is a commented line `runscripts yes(yes/no)`, you need to uncomment that line and next time when you do `ptr-get` install or something, it will automatically run pre or post install scripts for you.

**Comment by dlcusa** [comment]
If there is now a perpetual dependence on `python3-pip` why is it not in the `# Depend on:` statement in `Pkgfile`?
```
# Description: Easily download, build, install, upgrade, and uninstall Python packages.
# URL:         http://pypi.python.org/pypi/setuptools
# Maintainer:  6c37 Team, https://github.com/6c37/crux-ports/issues
# Depends on:  python3
```

I had been avoiding rerunning install scripts for updates, but I guess I need to even though that can break things (even though they're supposed to be sufficiently robust to not do that),  Thanks for pointing that out.  I'll let you know how this goes...

**Comment by dlcusa** [comment]
It went well--thanks for your support.

**Comment by rtlanceroad** [comment]
Thanks for the test. Adding `python3-pip` as a dependency of `python3-setuptools` will cause `cyclic dependencies` issue as we discussed before. But for `python3-six`, I'll add it as a dependency of `python3-setuptools`.

**Comment by dlcusa** [comment]
I understand not adding `python3-pip` to `Depends On` at this time, but will it not cease to be a problem when the older version is no longer around?  I guess I'm recommending a fuller explanation somewhere, probably in the readme and/or as plain old comment lines under or over the `Depends On:` statement.  IMHO, of course.

**Comment by rtlanceroad** [comment]
That made sense. I'll add it in the README.

**Comment by rtlanceroad** [comment]
And for the {pre-,post-}install scripts, I heard from Romster that he run them for years without any problem when I used crux at the very beginning. they should be safe to execute.

**Comment by dlcusa** [comment]
Interestingly, it was Romster who pointed out <https://github.com/pypa/setuptools/issues/950> on `#crux-devel` with incredulity regarding the thus far only response.

**Comment by rtlanceroad** [comment]
haha

**Comment by dlcusa** [comment]
So, does <https://github.com/pypa/setuptools/issues/958> resolve the problem?

**Comment by rtlanceroad** [comment]
I dont know, it looks quite promising. Now you see [install_dep() function runs assuming dependencies are not present](https://github.com/pypa/setuptools/blob/master/bootstrap.py#L92), let's wait some time, I'll test this on the next release.

**Comment by dlcusa** [comment]
Romster started a long and pertinent discussion on `#crux-devel` at 2017-02-03 10:02 UT -- it looks like he has solved this mess and python3 is headed for the `opt` collection.

**Comment by rtlanceroad** [comment]
Glad to hear it.

**Comment by rtlanceroad** [comment]
It(https://github.com/pypa/setuptools/pull/958) doesn't fix the issue, at least in 34.1.1. 
I removed `appdirs` `packaging` using `sudo pip3 uninstall appdirs packaging` then removed `python3-pip` using `prt-get remove python3-pip` and finally used `prt-get update -fr python3-setuptools --install-scripts`(because it is previously installed), and this was what I got:
```
$ sudo prt-get update -fr python3-setuptools --install-scripts
prt-get: updating /home/lee/crux-ports/python3-setuptools
Pkgfile: line 5: $'\302\240': command not found
=======> Building '/home/lee/crux-ports/python3-setuptools/python3-setuptools#34.1.1-1.pkg.tar.gz'.
bsdtar -p -o -C /home/lee/crux-ports/python3-setuptools/work/src -xf /home/lee/crux-ports/python3-setuptools/setuptools-34.1.1.zip
+ build
+ cd setuptools-34.1.1
+ python3 bootstrap.py
Regenerating egg_info
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/home/lee/crux-ports/python3-setuptools/work/src/setuptools-34.1.1/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/home/lee/crux-ports/python3-setuptools/work/src/setuptools-34.1.1/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/lee/crux-ports/python3-setuptools/work/src/setuptools-34.1.1/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
Traceback (most recent call last):
  File "bootstrap.py", line 97, in main
    run_egg_info()
  File "bootstrap.py", line 59, in run_egg_info
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'egg_info']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bootstrap.py", line 104, in <module>
    __name__ == '__main__' and main()
  File "bootstrap.py", line 100, in main
    with install_deps():
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "bootstrap.py", line 77, in install_deps
    import pip
ModuleNotFoundError: No module named 'pip'
=======> ERROR: Building '/home/lee/crux-ports/python3-setuptools/python3-setuptools#34.1.1-1.pkg.tar.gz' failed.
```
I see that if dependencies are not met, it stills needs `python3-pip` to download dependencies using `pip3`. Currently we can't package `python3-appdirs` and `python3-packaging` by seperate because there are _too much_ dependencies for those two.

**Comment by dlcusa** [comment]
Sounds like this issue needs to be reopened unless you want to drop the `6c37` versions for the `opt` versions (after a little shaking out).

**Comment by therealromster** [comment]
You should be able to drop python3 and setuptools and its dependencies now. I had seen the mess and decided to fix it up.

**Comment by rtlanceroad** [comment]
@therealromster  Thanks for bringing `python3` and `python3-setuptools` with its dependency into `opt`!
There are something I see that I think it can be improved:

- In [python3 Pkgfile](https://crux.nu/ports/crux-3.3/opt/python3/Pkgfile), I see you forcely link python3 binary to python3 by `ln -s python${version%.*} $PKG/usr/lib/$name`, nothing wrong, but actually there is an alternative way that can be used to keep python3 alive with python3, that use `make -j1 DESTDIR=$PKG altinstall` instead of `make -j1 DESTDIR=$PKG install`, The README under python3 source code mentioned it. just FYI :)

- About source URL, could we use `https://pypi.python.org/packages/source/s/six/six-$version.tar.gz` instead of `https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-$version.tar.gz` for `python3-six` as an example? same for `python3-appdirs` `python3-packaging` `python3-pip` `python3-pyparsing` `python3-setuptools`? 

Thanks for fix this mess again! I'll drop them when 3.3 is official out. :)

**Comment by therealromster** [comment]
I did try this `https://pypi.python.org/packages/source/${name:0:1}/$name/$name-$version.tar.gz` but i get errors for all but six. `<Code>NoSuchKey</Code>`

**Comment by therealromster** [comment]
I found the URL that works by chance:
`https://files.pythonhosted.org/packages/source/${name:0:1}/$name/$name-$version.tar.gz`

**Comment by rtlanceroad** [comment]
Okay, it will redirect to ` https://files.pythonhosted.org/packages/source/${name:0:1}/$name/$name-$version.tar.gz` anyway. :)

**Comment by rtlanceroad** [comment]
Those python modules which appear in `opt` just got removed.
