### ISSUE TITLE
neomutt: build issues with version 20170206

### ISSUE THREAD

**Issue by maraku** [6c37/crux-ports#87]
hey guys, i found a couple of problems with the neomutt Pkgfile:
- there's an md5 mismatch
- the tar file unpacks into a different naming scheme
- the prepare script is now a configure script
- there are trailing spaces in the Pkgfile 😄 

here's a patch/diff
```
diff --git a/neomutt/.footprint b/neomutt/.footprint
index 2882d0e..7cd5d58 100644
--- a/neomutt/.footprint
+++ b/neomutt/.footprint
@@ -17,4 +17,4 @@ drwxr-xr-x	root/root	usr/share/man/man1/
 drwxr-xr-x	root/root	usr/share/man/man5/
 -rw-r--r--	root/root	usr/share/man/man5/muttrc.5.gz
 drwxr-xr-x	root/root	usr/share/mutt/
--rw-r--r--	root/root	usr/share/mutt/manual.txt (EMPTY)
+-rw-r--r--	root/root	usr/share/mutt/manual.txt
diff --git a/neomutt/.md5sum b/neomutt/.md5sum
index c325bf7..040733a 100644
--- a/neomutt/.md5sum
+++ b/neomutt/.md5sum
@@ -1 +1 @@
-e3d67be3d63a1fd55c249649dfbed1cb  neomutt-20170206.tar.gz
+4919dec60991c40a5072617a54a07d87  neomutt-20170206.tar.gz
diff --git a/neomutt/Pkgfile b/neomutt/Pkgfile
index 5906bab..c3233d4 100644
--- a/neomutt/Pkgfile
+++ b/neomutt/Pkgfile
@@ -1,7 +1,7 @@
 # Description: Powerful text-based mail client with all the best feature patches.
 # URL:         https://www.neomutt.org/
 # Maintainer:  6c37 Team, https://github.com/6c37/crux-ports/issues
-# Depends on:  
+# Depends on:
 
 name=neomutt
 version=20170206
@@ -9,9 +9,9 @@ release=1
 source=(https://github.com/$name/$name/archive/$name-$version.tar.gz)
 
 build () {
-	cd $name-$name-$version
+	cd $name-$version
 
-	./prepare \
+	./configure \
 		--prefix=/usr \
 		--with-docdir=/usr/share/mutt \
 		--with-mailpath=/var/spool/mail \
@@ -31,6 +31,6 @@ build () {
 	make DESTDIR=$PKG install
 
 	find $PKG/usr/share/mutt/* ! -name manual.txt -delete
-	rm $PKG/usr/etc/{Muttrc,mime.types}.dist 
+	rm $PKG/usr/etc/{Muttrc,mime.types}.dist
 	rm $PKG/usr/share/man/man5/{mmdf.5,mbox.5}
 }
```

**Comment by rtlanceroad** [comment]
@maraku Hi, thanks for the report, I just tested it built fine here. 

> there's an md5 mismatch
I dont have this issue, maybe your download is corrupted?

> the tar file unpacks into a different naming scheme
> the prepare script is now a configure script
Indeeded. The upstream packed the tarball using `$name-$name-$version` and replaced `configure` script with `prepare` script. These are detailed in `INSTALL` file under neomutt source code directory.

 > there are trailing spaces in the Pkgfile 😄
I don't see trailing spaces, but there are indeed some problems like `manual.txt` and mime types aren't deleted. I'll fix them.

**Comment by rtlanceroad** [comment]
I think I am wrong, @onodera-punpun is intended to keep `manual.txt`(I guess for neomutt setup although it's an empty file) and mime.types(I guess for browsering with correct types match). Sorry I'll keep them as they are.

**Comment by rtlanceroad** [comment]
What do you think? @maraku

**Comment by maraku** [comment]
sorry @rtlanceroad, it seems my downloads got mixed up (i use PKGMK_SOURCE_DIR=/usr/ports/src), i had downloaded https://github.com/neomutt/neomutt/releases/download/neomutt-20170206/neomutt-20170206.tar.gz (not the Source Code tar gz download)

the other download still is the source code, but it contains a configure script and it unpacks into neomutt-20170206 rather than neomutt-neomutt-20170206

**Comment by rtlanceroad** [comment]
@maraku If you download a different source tarball,  you need to change Pkgfile accordingly to fix your needs, like source code name structure, the build process etc.. and you may want to pass `-im` and `-if` to prt-get right now.

**Comment by rtlanceroad** [comment]
It quite makes a difference.

**Comment by rtlanceroad** [comment]
I'll close it now
