### ISSUE TITLE
Where is your public key? (6c37.pub)

### ISSUE THREAD

**Issue by nihilismus** [6c37/crux-ports#88]
Hi, I'm trying to use these ports but I'm getting:

```
=======> ERROR: Signature mismatch found:
+ echo 'signify: can'\''t open /etc/ports/6c37.pub for reading: No such file or directory'
```

Where i can find your public key?

**Comment by rtlanceroad** [comment]
It's here: https://github.com/6c37/cross/tree/master/keys `6c37-git` and `6c37-dropin` keys are also there.

**Comment by onodera-punpun** [comment]
I submitted the new URL and keys to the portdb btw, so they should show up on there as well someday.
