### ISSUE TITLE
emacs: removed important files

### ISSUE THREAD

**Issue by nihilismus** [6c37/crux-ports#89]
I was getting some errors since this commit: https://github.com/6c37/crux-ports/commit/5b7cc73d19f1667fb322afd584c612aa0bdf345e

```
Eager macro-expansion failure: (file-error "Loading charset map" "No such file or directory" "JISX0208")
Eager macro-expansion failure: (file-error "Loading charset map" "No such file or directory" "JISX0208")
Error loading autoloads: (file-error Loading charset map No such file or directory JISX0208)
Emacs Prelude is now refreshing its package database...
Failed to download ‘gnu’ archive.
Package refresh done
Failed to download ‘melpa’ archive.
 done.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Loading charset map: No such file or directory, JISX0208
```

To fix these issues I removed these lines from emacs/Pkgfile:

```
find $PKG -name '*README*' -delete
find $PNG -name '*NEWS*' -delete
find $PKG -name COPYING -delete
find $PKG/usr/share/emacs/$version/etc -name '[A-Z]*' -delete
```

As i can understand in your commit you are deleting some `*.el` and `*.map` files required by Emacs.

**Comment by rtlanceroad** [comment]
@nihilismus Thanks for reporting. I found the problem. It(find $PKG/usr/share/emacs/$version/etc -name '[A-Z]*' -delete) was expected to delete junk files from A to Z under `/usr/share/emacs/$version/etc`by this commit https://github.com/6c37/crux-ports/commit/5b7cc73d19f1667fb322afd584c612aa0bdf345e, but unfornately it also deleted charset. So i'll fix this.
For any README, NEWS and COPYING, `prtverify` will treat them as junk files which need to be deleted.

**Comment by rtlanceroad** [comment]
@nihilismus Try sync repo then update emacs again, it should be fixed by commit https://github.com/6c37/crux-ports/commit/eb194bc05e834082a5e5cf5d0d253c4472158cee .
