### ISSUE TITLE
zathura: rm -r ${PKG}/usr/share is not good for user

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#9]
I don't think removing ${PKG}/usr/share is a good idea, because it also removes ${PKG}/usr/share/applications/zathura.desktop  this desktop entry.  People who are using xfce4(including me) will not find it in xfce4 menu.

**Comment by kori** [comment]
Oh, this might be a bug.
I did rm $PKG/usr/share in the girara port because it was an empty dir but for zathura it might have useful things.

**Comment by kori** [comment]
Fixed in c3240d9.

**Comment by rtlanceroad** [comment]
Thanks
