### ISSUE TITLE
Xonotic footprint mismatch

### ISSUE THREAD

**Issue by jmf** [6c37/crux-ports#91]
Apparently, the xonotic package was built without fakeroot, messing up the permissions:

=======> ERROR: Footprint mismatch found:
MISSING   drwxr-xr-x      skrzyp/users    usr/
MISSING   drwxr-xr-x      skrzyp/users    usr/bin/
MISSING   -rwxr-xr-x      skrzyp/users    usr/bin/xonotic-glx
MISSING   drwxr-xr-x      skrzyp/users    usr/share/
MISSING   drwxr-xr-x      skrzyp/users    usr/share/xonotic/
MISSING   drwxr-xr-x      skrzyp/users    usr/share/xonotic/data/
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/font-unifont-20150825.pk3
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/font-xolonium-20150825.pk3
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/xonotic-20150825-data.pk3
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/xonotic-20150825-maps.pk3
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/xonotic-20150825-music.pk3
MISSING   -rw-rw-r--      skrzyp/users    usr/share/xonotic/data/xonotic-20150825-nexcompat.pk3
MISSING   -rw-r--r--      skrzyp/users    usr/share/xonotic/key_0.d0pk
NEW       drwxr-xr-x      root/root       usr/
NEW       drwxr-xr-x      root/root       usr/bin/
NEW       -rwxr-xr-x      root/root       usr/bin/xonotic-glx
NEW       drwxr-xr-x      root/root       usr/share/
NEW       drwxr-xr-x      root/root       usr/share/xonotic/
NEW       drwxr-xr-x      root/root       usr/share/xonotic/data/
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/font-unifont-20150825.pk3
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/font-xolonium-20150825.pk3
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/xonotic-20150825-data.pk3
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/xonotic-20150825-maps.pk3
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/xonotic-20150825-music.pk3
NEW       -rw-rw-r--      root/root       usr/share/xonotic/data/xonotic-20150825-nexcompat.pk3
NEW       -rw-r--r--      root/root       usr/share/xonotic/key_0.d0pk
=======> ERROR: Building '/usr/ports/6c37/xonotic/xonotic#0.8.1-1.pkg.tar.gz' failed.

**Comment by rtlanceroad** [comment]
@jmf  Thanks for reporting, Unfortunately, I can't rebuild because the xonotic source code is nearly 1G and I don't have fast internet connection to download it.
@skrzyp Could you rebuild it with root previlige instead and update the footprint?

**Comment by rtlanceroad** [comment]
fixed by commit 01d20e30126fb4c808f2a5b72d32d2734902eef8
