### ISSUE TITLE
nvidia-340 fails to build on kernel >=4.9

### ISSUE THREAD

**Issue by justinbloomfield** [6c37/crux-ports#92]
Changing version to 340.102 worked for me, for both nvidia-340 and nvidia-340-32

**Comment by rtlanceroad** [comment]
@justinbloomfield Thanks for reporting. I don't have pc with nvidia cards, therefore I can't do a reliable update for them. 
@onodera-punpun Could you update both packages?

**Comment by onodera-punpun** [comment]
Thanks for reporting this, updated them.
