### ISSUE TITLE
Kicad new release 4.0.6

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#93]
I can't update kicad to 0.4.6 because wxpython failed to build for me and it is trying to find `gstreamer0.10` and `gstreamer-plugin-base-0.10` cppflags and libraries which are obsolete by Crux Linux already. I'll see @therealromster and I can bring them back....

**Comment by rmull** [comment]
Thanks, I'll check it out, possibly tomorrow.

**Comment by rmull** [comment]
Hey, just out of curiosity, did you mistype 0.4.6? 4.0.6 is the new release. 4.0.6 built for me, though I'm not in a clean environment - I just want to make sure you didn't accidentally set the Pkgfile up to pull 0.4.6 instead of 4.0.6.

**Comment by rtlanceroad** [comment]
Yes, sorry I mistyped. If it built for you, please push :)

**Comment by rtlanceroad** [comment]
I found the reason why fresh 3.3 install didn't have wxpython built: because in `opt` repo, 3.3 lacked `gstreamer-compat` and `gst-plugins-base-compat`. well 3.2 had . If ones updated 3.2 to 3.3, they still had those two installed.

**Comment by rmull** [comment]
Good find. I am on a 3.2 -> 3.3 platform, so I must have had those deps. Is the solution to package those ports for 3.3 and include them in the dep list for kicad?

**Comment by rtlanceroad** [comment]
I will talk to @therealromster first and see if he can port them to 3.3. If not, I'll port them to 6c37. They are not the deps for kicad, for wxpython instead. :)

**Comment by rmull** [comment]
Great, thanks. I'll keep an eye on this topic.

**Comment by rtlanceroad** [comment]
@rmull I've pushed a commit(acc8c5c8622e8fa004d493fbcef68b3eb352dfd4), could you check? It should work.

**Comment by rmull** [comment]
kicad 4.0.6 and the new deps build fine for me. I won't have a chance to run it until later tonight, but I'm feeling confident. Thanks again for resolving this.

**Comment by rmull** [comment]
I get this message printed to the console when I run kicad:

23:50:41: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).

The program would otherwise appear to be running normally. I'm not quite sure what to make of this.

**Comment by rtlanceroad** [comment]
Odd. I run kicad from console, and nothing wrongness appears.  From what I see, your wxpython compiled with gcc 5.4.0 and is not compatible with new C++ ABI. Maybe rebuild wxpython with gcc 6.3.0 and furthermore rebuild kicad? :)

**Comment by rmull** [comment]
Rebuilding wxpython and kicad didn't seem to fix it, so I rebuilt everything on my system and it loads without warning now. Closing this.
