### ISSUE TITLE
failed to update package cups

### ISSUE THREAD

**Issue by zypeh** [6c37/crux-ports#95]
```
=======> ERROR: Footprint mismatch found:
NEW             lrwxrwxrwx           root/root           usr/lib/cups/backend/https -> ipp
NEW             lrwxrwxrwx           root/root           usr/lib/cups/backend/ipps -> ipp
=======> ERROR: Building '/usr/ports/packages/cups#2.2.3-1.pkg.tar.gz' failed.
```

**Comment by zypeh** [comment]
Or can I just ignore the footprint mismatch? Since there is no any missing file.

**Comment by rtlanceroad** [comment]
@zypeh Yeah you can just ignore the footprint error by passing `-if` to `prt-get` or `pkgmk`.  Btw, it's not our bug, right? So next time, please ask on #crux channel hosted on freenode. :)
