### ISSUE TITLE
Gvfs and xdg-user-dirs install problem 

### ISSUE THREAD

**Issue by lounqe** [6c37/crux-ports#97]
Hi i got this problem today installing gvfs and the same error also for xdg-user-dirs

warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl

I checked the link and its working also docbook-xsl is alreay installed i dont know this problem ?

**Comment by onodera-punpun** [comment]
Hmm is this during compilation? I just build `xdg-user-dirs` myself, and I didn't get any errors.

**Comment by onodera-punpun** [comment]
Oh and btw, both `docbook-xsl` and `docbook-xml` have a `post-install`, did you run these?

**Comment by rtlanceroad** [comment]
@lounqe Yeah. just @onodera-punpun said, run `prt-get update -fr docbook-xml docbook-xsl --install-scripts` to execute post-scripts for those two packages, then you can install `xdg-user-dirs` and `gvfs` without problems. :)

**Comment by lounqe** [comment]
ok ,it worked ,thanks

**Comment by onodera-punpun** [comment]
no problem.
