### ISSUE TITLE
Move firefox-gtk2 to orphan? 

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports#99]
Esp @onodera-punpun What do you think? This is the error I get when building firefox 53.0:
```
mozbuild.configure.options.InvalidOptionError: 'cairo-gtk2' is not one of 'cairo-windows', 'cairo-gtk3', 'cairo-cocoa', 'cairo-uikit', 'cairo-android', 'cairo-gonk'
*** fix above errors and then restart with\
                      "make -f client.mk build"
```
It seems that option `ac_add_options --enable-default-toolkit=cairo-gtk2` is no longer available now. Cairo-gtk2 is the 2D library for firefox, if it's no longer listed as a build option, I am kinda sure that firefox gtk2 version is dead. What do you think?

**Comment by onodera-punpun** [comment]
Yeah I no longer use it myself as well, I ok on this.

**Comment by rtlanceroad** [comment]
Removed by commit ddf4c243ba563812c5c716aa082de21293bff43b .
